### ISSUE TITLE
During last KSPAVC update/build, .version file update seems not to have made it into the release package?

### ISSUE THREAD

**Issue by StoneBlue** [linuxgurugamer/KSPAddonVersionChecker#22]
LGG, just fresh installed KSPAVC, and noted the .version file in the release package lists v1.3.1.0, KSP VERSION 1.5.1, MAX VERSION 1.5.1... instead of 1.7.2, based on your version bump release note, I'm assuming it is *supposed* to list 1.7.2? vOv

I also note the .version file in the /GameData folder in the master, seems *not* to be the same as the one listed in the master itself? It lists v1.3.0.4, for KSP 1.5.1, 1.5.1 .. vOv

Not sure if that matters as a seperate issue, due to your release package build process?

i also note, with the 1.3.1.0 release, KSPAVC shows itself as up to date ingame, on 1.7.3, yet with the .version file only listing KSP 1.5.1, 1.5.1? vOv

**Comment by linuxgurugamer** [comment]
Please check the newest release for 1.8
