### ISSUE TITLE
MiniAVC ZIP folder structure looks like it's not what was intended

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/KSPAddonVersionChecker#36]
Hi @linuxgurugamer,

This is what's in the MiniAVC ZIP file right now:

https://github.com/linuxgurugamer/KSPAddonVersionChecker/releases/download/1.4.1.5/MiniAVC-V2-1.8.0-2.0.0MiniAVC.zip

```
└── [4.0K May 21 10:55]  GameData/
    └── [4.0K Jun 28  2020]  MiniAVC-V2/
        ├── [ 422 Jun 28  2020]  MiniAVC-V2.version
        ├── [ 14K Jun 28  2020]  MiniAVC-V2.dll.mdb
        ├── [ 44K Jun 28  2020]  MiniAVC-V2.dll
        └── [4.0K Jun 28  2020]  Plugins/
            └── [   0 Jun 28  2020]  placeholder.txt
```

It looks like the intention here was to put the plugin in the Plugins folder, but it's in `GameData/MiniAVC-V2` (the parent folder of Plugins) instead, and the Plugins folder only contains `placeholder.txt`. I'm guessing there was a mix-up in the build script that generates this file.

Noticed while checking up on this repo for KSP-CKAN/CKAN#2490.

## Suggestions

- Remove the Plugins folder to reduce confusion; _OR_
- Move the plugin to the Plugins folder and remove `placeholder.txt` from the release ZIP

**Comment by linuxgurugamer** [comment]
I've updated the MiniAVC-V2 zip file to fix the location of the dll

**Comment by HebaruSan** [comment]
Cool, looks fixed now. The `placeholder.txt` is still there and probably not needed in the release ZIP, but the Plugins folder contains the plugin now.

**Comment by linuxgurugamer** [comment]
If I do any more releases (most likely not), I'll remove that file, but not worth a release for that
