### ISSUE TITLE
KSP-AVC

### ISSUE THREAD

**Issue by MollyDolly** [linuxgurugamer/KSPAddonVersionChecker#37]
hi i'm not sure if i'm to post here, so i'm going to take the leap.

its probably minor but I get a warning about the incorrect file location for KSP-AVC.dll+
the warning is a follows. 
C:\Kerbal Space Program 1.12.1\GameData\KSP-AVC\Plugins was incorrect as far a  AVC was considered
It said the KSP.AVC.dll needed to be in C:\Kerbal Space Program 1.12.1\GameData\KSP-AVC. I moved warning gone.

**Comment by linuxgurugamer** [comment]
Fixed in release 1.4.1.9
